from reportlab.platypus import (
    SimpleDocTemplate,
    Paragraph,
    Spacer,
    Table,
    TableStyle
)
from reportlab.lib import colors
from reportlab.lib.styles import getSampleStyleSheet
from reportlab.lib.enums import TA_CENTER
from reportlab.lib.units import inch


def generate_pdf(analysis, filename):
    doc = SimpleDocTemplate(filename)
    styles = getSampleStyleSheet()

    title_style = styles["Title"]
    title_style.alignment = TA_CENTER

    heading_style = styles["Heading2"]
    normal_style = styles["BodyText"]

    elements = []

    # ==========================
    # Title
    # ==========================

    elements.append(Paragraph("SUN AI Security Analysis Report", title_style))
    elements.append(Spacer(1, 0.25 * inch))

    # ==========================
    # Summary Table
    # ==========================

    severity = getattr(analysis, "severity_score", "N/A")
    confidence = getattr(analysis, "confidence", "N/A")

    table_data = [
        ["Filename", analysis.filename],
        ["Risk Level", analysis.risk_level],
        ["Attack Type", analysis.attack_type],
        ["Severity Score", severity],
        ["Confidence", f"{confidence}%"]
    ]

    table = Table(table_data, colWidths=[160, 300])

    table.setStyle(
        TableStyle(
            [
                ("BACKGROUND", (0, 0), (0, -1), colors.darkblue),
                ("TEXTCOLOR", (0, 0), (0, -1), colors.white),
                ("BACKGROUND", (1, 0), (1, -1), colors.beige),
                ("GRID", (0, 0), (-1, -1), 1, colors.black),
                ("BOTTOMPADDING", (0, 0), (-1, -1), 8),
                ("FONTNAME", (0, 0), (-1, -1), "Helvetica"),
                ("VALIGN", (0, 0), (-1, -1), "MIDDLE"),
            ]
        )
    )

    elements.append(table)
    elements.append(Spacer(1, 0.3 * inch))

    # ==========================
    # Summary
    # ==========================

    elements.append(Paragraph("Summary", heading_style))
    elements.append(
        Paragraph(
            str(analysis.summary),
            normal_style
        )
    )

    elements.append(Spacer(1, 0.2 * inch))

    # ==========================
    # Recommendations
    # ==========================

    elements.append(Paragraph("Recommendations", heading_style))

    recommendations = analysis.recommendations

    if isinstance(recommendations, list):
        for item in recommendations:
            elements.append(
                Paragraph(f"• {item}", normal_style)
            )
    else:
        elements.append(
            Paragraph(
                str(recommendations),
                normal_style
            )
        )

    elements.append(Spacer(1, 0.2 * inch))

    # ==========================
    # Footer
    # ==========================

    elements.append(
        Paragraph(
            "<b>Generated by SUN AI - AI Powered Cybersecurity Analysis System</b>",
            styles["Italic"],
        )
    )

    doc.build(elements)

    return filename